# Generated by Django 4.2.11 on 2024-06-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='make',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Buick'), (2, 'Cadillac'), (2, 'Chevrolet')], null=True, verbose_name='Vehicle Model Make/Brand'),
        ),
    ]
