# Generated by Django 4.2.11 on 2024-04-13 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_3', '0002_engine_vehicle_model_vehicle_engine_vehicle_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Seller Name')),
                ('vehicle', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_sellers', related_query_name='vehicle_seller', to='chapter_3.vehicle', verbose_name='Vehicles')),
            ],
        ),
    ]
