# Generated by Django 4.2.11 on 2024-06-07 05:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_3', '0002_vehiclemodel_make'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vehicle',
            managers=[
                ('buicks', django.db.models.manager.Manager()),
            ],
        ),
    ]
