# Generated by Django 4.2.11 on 2024-04-13 06:54

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_3', '0003_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'ordering': ['name'], 'verbose_name': 'Vehicle Model', 'verbose_name_plural': 'Vehicle Models'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Buick'), (2, 'Cadillac'), (2, 'Chevrolet')], null=True, verbose_name='Vehicle Make/Brand'),
        ),
        migrations.AddIndex(
            model_name='vehiclemodel',
            index=models.Index(fields=['name'], name='chapter_3_v_name_7ccb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclemodel',
            index=models.Index(fields=['-name'], name='desc_name_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclemodel',
            index=models.Index(models.OrderBy(django.db.models.functions.text.Lower('name'), descending=True), name='lower_name_idx'),
        ),
    ]
