# Generated by Django 4.2.11 on 2024-06-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_3', '0003_alter_vehicle_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Buick'), (2, 'Cadillac'), (3, 'Chevrolet')], null=True, verbose_name='Vehicle Make/Brand'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='make',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Buick'), (2, 'Cadillac'), (3, 'Chevrolet')], null=True, verbose_name='Vehicle Model Make/Brand'),
        ),
    ]
